### Python para Data Science

#### Bibliotecas

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
def znorm(x: np.ndarray) -> np.ndarray:
    return (x - min(x))  / (max(x) - min(x))

In [3]:
vetor_a = np.array(list(random.randint(1, 20) for i in range(20)))
vetor_b = np.array(list(random.randint(1, 20) for i in range(20)))
print(vetor_a, '\n', vetor_b)

[ 1  7 13 16  8 12  8  6 13 14 13  7  2  2 20 13  3  7 13  8] 
 [15 16  3 16 14 18 10  4 13 18  1  1 19 15  5  9 18 16  8 18]


In [4]:
norm_vetor_a = znorm(vetor_a)
norm_vetor_b = znorm(vetor_b)
print(norm_vetor_a, '\n', norm_vetor_b)

[0.         0.31578947 0.63157895 0.78947368 0.36842105 0.57894737
 0.36842105 0.26315789 0.63157895 0.68421053 0.63157895 0.31578947
 0.05263158 0.05263158 1.         0.63157895 0.10526316 0.31578947
 0.63157895 0.36842105] 
 [0.77777778 0.83333333 0.11111111 0.83333333 0.72222222 0.94444444
 0.5        0.16666667 0.66666667 0.94444444 0.         0.
 1.         0.77777778 0.22222222 0.44444444 0.94444444 0.83333333
 0.38888889 0.94444444]


In [5]:
ab_matrix = np.array([vetor_a, vetor_b]).transpose()
norm_ab_matrix = np.array([norm_vetor_a, norm_vetor_b]).transpose()
print(ab_matrix, '\n', norm_ab_matrix)

[[ 1 15]
 [ 7 16]
 [13  3]
 [16 16]
 [ 8 14]
 [12 18]
 [ 8 10]
 [ 6  4]
 [13 13]
 [14 18]
 [13  1]
 [ 7  1]
 [ 2 19]
 [ 2 15]
 [20  5]
 [13  9]
 [ 3 18]
 [ 7 16]
 [13  8]
 [ 8 18]] 
 [[0.         0.77777778]
 [0.31578947 0.83333333]
 [0.63157895 0.11111111]
 [0.78947368 0.83333333]
 [0.36842105 0.72222222]
 [0.57894737 0.94444444]
 [0.36842105 0.5       ]
 [0.26315789 0.16666667]
 [0.63157895 0.66666667]
 [0.68421053 0.94444444]
 [0.63157895 0.        ]
 [0.31578947 0.        ]
 [0.05263158 1.        ]
 [0.05263158 0.77777778]
 [1.         0.22222222]
 [0.63157895 0.44444444]
 [0.10526316 0.94444444]
 [0.31578947 0.83333333]
 [0.63157895 0.38888889]
 [0.36842105 0.94444444]]


In [55]:
multiplied_array = np.array([ab_matrix * norm_ab_matrix])
multiplied_array

array([[[ 2.21052632,  0.33333333],
        [ 6.94736842,  1.11111111],
        [18.        , 15.11111111],
        [ 3.78947368,  0.11111111],
        [ 6.94736842,  6.11111111],
        [16.10526316, 11.66666667],
        [ 1.05263158, 17.        ],
        [ 6.94736842,  4.        ],
        [ 4.73684211, 10.11111111],
        [ 5.78947368,  8.66666667],
        [12.63157895, 10.11111111],
        [ 0.        ,  0.        ],
        [ 0.10526316,  7.33333333],
        [ 9.57894737,  7.33333333],
        [ 8.21052632,  4.        ],
        [20.        , 19.        ],
        [ 5.78947368, 11.66666667],
        [12.63157895,  6.11111111],
        [ 1.57894737,  1.66666667],
        [20.        ,  1.66666667]]])

In [74]:
ab_matrix.dot(norm_ab_matrix.transpose())

array([[17.25696594, 11.21981424,  4.32817337,  1.84829721, 17.25696594,
        16.08668731, 17.73065015,  7.88544892,  5.29411765,  7.97832817,
        12.64086687,  2.79566563, 14.7120743 ,  2.84210526, 21.        ,
        20.36842105,  8.72136223, 18.3622291 ,  5.49845201, 10.58823529],
       [11.82043344,  8.11145511,  5.09597523,  2.02167183, 11.82043344,
        11.9876161 , 12.60990712,  5.73065015,  3.52941176,  8.00309598,
        10.47987616,  3.6006192 , 10.75541796,  4.73684211, 17.        ,
        15.94736842,  8.18266254, 13.6625387 ,  4.92879257,  7.05882353],
       [ 5.34365325,  5.51083591, 11.52321981,  4.18266254,  5.34365325,
         9.60990712,  7.7120743 ,  4.01547988,  1.17647059, 14.59752322,
        12.61609907,  8.91950464,  7.79566563, 14.21052632, 19.        ,
        15.84210526, 13.25386997, 10.86996904,  7.25696594,  2.35294118],
       [ 3.45510836,  3.02786378,  4.77399381,  1.75541796,  3.45510836,
         4.99690402,  4.40247678,  2.18266254,  